version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: Install tools
          command: make install-tools
      - run:
          name: Check
          command: make check
      - run:
          name: Test
          command: make test
