version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: Install tools
          command: make install-tools
      - run:
          name: Check
          command: make check
      - run:
          name: Test
          command: make test
      - run:
          name: Coverage tests
          command: make test-with-cover
      - run:
          name: Coverage push
          command: bash <(curl -s https://codecov.io/bash)
